describe('Notes Application E2E Tests', () => {
  
  beforeEach(() => {
    cy.visit('http://localhost:80');
  });

  it('should create a new note with specific color and tags', () => {
    const title = 'E2E Test Note';
    const content = 'This is a test content generated by Cypress';
    cy.get('button').contains('Add New Note').click();
    cy.get('input[placeholder*="Title"]').type(title);
    cy.get('textarea[placeholder*="Write your note here..."]').type(content);
    cy.get('button[style*="background-color"]').eq(1).click();
    cy.get('button').contains('#Work').click();
    cy.get('button').contains('#Ideas').click();

    cy.get('button').contains('Save').click();

    cy.contains(title).should('be.visible');
    cy.contains('#Work').should('be.visible');
  });

  it('should update an existing note title and color', () => {
    cy.get('section .group').first().within(() => {
      cy.get('mat-icon').contains('edit').click({ force: true });
    });

    cy.get('input[placeholder*="Title"]').clear().type('Updated Title');
    
    cy.get('button[style*="background-color"]').last().click();

    cy.get('button').contains('Update').click();

    cy.contains('Updated Title').should('be.visible');
  });

  it('should filter notes by search query and tags', () => {
    cy.get('aside input[type="text"]').type('Updated');

    cy.get('aside button').contains('Work').click();
    cy.get('section .group').should('have.length.at.least', 1);
    cy.contains('Updated').should('be.visible');
  });

  it('should filter notes by clicking a day in the calendar', () => {
    const today = new Date().getDate();
        cy.get('app-custom-calendar').within(() => {
      cy.get('div.h-10.w-10.flex').contains(today.toString()).click();
    });

    cy.get('app-custom-calendar .bg-gray-500').should('contain', today);
  });

  it('should delete a note and show confirmation', () => {
    cy.on('window:confirm', () => true);

    cy.get('section .group').first().within(() => {
      cy.get('mat-icon').contains('delete').click({ force: true });
    });

    cy.contains('Updated Title').should('not.exist');
  });

});